server:
  port: 7070
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri:
          #username:
          #password:
          search-paths: config-data
          default-label: main
  security:
    user:
      name: root
      password: s3cr3t