server:
  port: 8081
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

spring:
  jpa:
    hibernate.ddl-auto: update
    generated-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdb.Driver
    url: jdbc:mysql://localhost:3306/ms-catalogo
    username: root
    password: